// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

// PostAssetCreateJSONBody defines parameters for PostAssetCreate.
type PostAssetCreateJSONBody struct {
	AssetId     string  `json:"asset_id"`
	CreatedAt   string  `json:"created_at"`
	DeletedAt   *string `json:"deleted_at,omitempty"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	Ticker      string  `json:"ticker"`
	UpdatedAt   string  `json:"updated_at"`
}

// PutAssetsAssetIdJSONBody defines parameters for PutAssetsAssetId.
type PutAssetsAssetIdJSONBody struct {
	AssetId     string  `json:"asset_id"`
	CreatedAt   string  `json:"created_at"`
	DeletedAt   *string `json:"deleted_at,omitempty"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	Ticker      string  `json:"ticker"`
	UpdatedAt   string  `json:"updated_at"`
}

// PostAssetCreateJSONRequestBody defines body for PostAssetCreate for application/json ContentType.
type PostAssetCreateJSONRequestBody PostAssetCreateJSONBody

// PutAssetsAssetIdJSONRequestBody defines body for PutAssetsAssetId for application/json ContentType.
type PutAssetsAssetIdJSONRequestBody PutAssetsAssetIdJSONBody
